name: Setup

description: Setup Node.js, cache and install dependencies

inputs:
  node_version:
    description: Node.js version
    required: false
    default: '16'

runs:
  using: composite
  steps:
    - name: Checkout all commits
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup git user to "🤖 JMChambers Bot"
      shell: bash
      run: git config user.email "-" && git config user.name "🤖 JMChambers Bot"

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        # This doesn't just set the registry url, but also sets
        # the right configuration in .npmrc that reads NPM token
        # from NPM_AUTH_TOKEN environment variable.
        # It actually creates a .npmrc in a temporary folder
        # and sets the NPM_CONFIG_USERCONFIG environment variable.
        registry-url: https://registry.npmjs.org

    - name: Install pnpm
      uses: pnpm/action-setup@v2.0.1
      id: pnpm-install
      with:
        version: 7
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install
